current_version = "0.5.0"

[[files]]
path = "Cargo.toml"
search = "version = \"{{current_version}}\""
replace = "version = \"{{new_version}}\""

[[files]]
path = "pyproject.toml"
search = "version = \"{{current_version}}\""
replace = "version = \"{{new_version}}\""

[[files]]
path = "doc/conf.py"
search = "release = \"{{current_version}}\""
replace = "release = \"{{new_version}}\""

[[files]]
path = "CHANGELOG.md"
search = "# Changelog"
replace = """
# Changelog

## v{{new_version}} - {{now|date}} (JST)
"""

[[files]]
path = "doc/usage/installation.rst"
search = """
   curl -L https://github.com/attakei/age-cli/releases/download/v{{current_version}}/age-v{{current_version}}_linux.zip | bsdtar x -
   chmod +x age-v{{current_version}}/age
   cp age-v{{current_version}}/age /path/to/bin/
"""
replace = """
   curl -L https://github.com/attakei/age-cli/releases/download/v{{new_version}}/age-v{{new_version}}_linux.zip | bsdtar x -
   chmod +x age-v{{new_version}}/age
   cp age-v{{new_version}}/age /path/to/bin/
"""

# This file has other replace target, but currently not supported.
[[files]]
path = ".github/release-body.md"
search = "- Changelog is https://github.com/attakei/age-cli/blob/v{{current_version}}/CHANGELOG.md"
replace = "- Changelog is https://github.com/attakei/age-cli/blob/v{{new_version}}/CHANGELOG.md"
